fix(mvdownload): check if file exists

diff --git a/bin/mvdownload b/bin/mvdownload
--- a/bin/mvdownload
+++ b/bin/mvdownload
@@ -7,4 +7,9 @@ if [ $# -ne 2 ]; then
     exit 1
 fi
 
+if [ ! -f "$DOWNLOADS_DIRECTORY/$1" ]; then
+    echo "not found: $DOWNLOADS_DIRECTORY/$1"
+    exit 1
+fi
+
 mv "$DOWNLOADS_DIRECTORY/$1" "$2"
