fix: nicer CLI for installation and `dot` scripts

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -2,18 +2,34 @@
 #
 # Run all dotfiles installers.
 #
-# Yoinked from https://github.com/holman/dotfiles/blob/master/script/install
+# Adapted from https://github.com/holman/dotfiles/blob/master/script/install
 
 set -e
 
 cd "$(dirname $0)"/..
 
 
-GREEN='\033[0;32m'
-FGRESET='\033[0m' # No Color
+info () {
+    printf "\r  [\033[00;34minfo\033[0m] %s\n" "$1"
+}
+
+fail () {
+  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
+  echo ''
+  exit 1
+}
+
+
 # find the installers and run them iteratively
 find . -maxdepth 2 -name install.sh -not -path './scripts/*' -not -path '*.git*' | while read installer
-do sh -c "
-    echo -e \"$FGGREEN${installer}$FGRESET\" && ${installer}" 
+do 
+    info "Installing '$installer'"
+    if [ -x "$installer" ]; then
+        "$installer"
+    else 
+        fail "Execution is not authorized for install script '$installer'"
+    fi
 done
+
+info "Ran all installers. Consider restarting zsh (exec zsh)."
 
